

#' Sample runModel function for Atlantis. It writes the calibrated
#' param (\code{param} argument) into a CSV file that will
#' overwrite the atlantis forcing files.
#' @param Parameter array.
#' @param Parameter names
#' @return A list containing all the variables
#' used in the calibration
runModel  = function(param, names, ...) {

    # set parameter names
    names(param) = names
    param = exp(param)
    write.table(param, file="calibration-parameters.csv", sep=",",
                col.names=FALSE, quote=FALSE)
    mum.factor = grep(x=names, pattern="mum")
    BHalpha.factor = grep(x=names, pattern="BHalpha")
    mq.factor = grep(x=names, pattern="mQ")
    KDENR.factor = grep(x=names, pattern="KDENR_")
    bio.prm = "AMPSbioparam_mv1_2024_V10.prm"
    bio.lines = readLines(bio.prm)

    for (i in 1:length(mum.factor)){
      species <- names[mum.factor[i]]
      factor  <- param[mum.factor[i]]
      species <- sub("mum_", "", species)
      species <- sub("_factor", "", species)

      bio.lines = atlantis2ls::edit_param_mum_sp(bio.lines, factor, species)
    }
    for (i in 1:length(BHalpha.factor)){
      species <- names[BHalpha.factor[i]]
      factor  <- param[BHalpha.factor[i]]
      species <- sub("BHalpha_", "", species)
      species <- sub("_factor", "", species)
      
      bio.lines = atlantis2ls::edit_param_BHalpha_sp(bio.lines, factor, species)
    }
    
    for (i in 1:length(KDENR.factor)){
      species <- names[KDENR.factor[i]]
      factor  <- param[KDENR.factor[i]]
      species <- sub("KDENR_", "", species)
      species <- sub("_factor", "", species)
      bio.lines = atlantis2ls::edit_param_KDENR_sp(bio.lines, factor, species)
    }
    
    for (i in 1:length(mq.factor)){
      species <- names[mq.factor[i]]
      factor  <- param[mq.factor[i]]
      species <- sub("_mQ_factor", "", species)
      bio.lines = atlantis2ls::edit_param_mq_sp(bio.lines, factor, species)
    }
    
    writeLines(bio.lines, "bio.prm")

    #TODO: Improve biomass function
    #TODO: replace for loop


path = getwd()

##########################################################################################
    # run Atlantis
    sh.file = "amps_cal.sh"
    atlantis2ls::run_atlantis(path = path, sh.file = sh.file)


##########################################################################################
    # read Atlantis outputs
    # path = "/home/atlantis/psatlantismodel/Atlantis_Calibration/RUN_9_25_2024/i21"

    prefix = "outputFolder/AMPS"
    bio.prm = "AMPSbioparam_mv1_2024_V10.prm"
    fg.file <- paste0(path,"/PugetSoundAtlantisFunctionalGroups_2024_V1.csv")
    
    log_file <- "parallel_log_read_atlantis.txt"

    
    # library(ncdf4)
    # nc <- ncdf4::nc_open(paste0(path, "/outputFolder/AMPS_OUT.nc"))
    # volumes <- ncdf4::ncvar_get(nc, "volume")
    # volumes_arr <- array(data = unlist(volumes),dim = dim(volumes)[c(1,dt.timestep)]) # box/layer volumes
    # 
    outputs <- atlantis2ls::read_atlantis(path = path, prefix = prefix, fg.file = fg.file, 
        txt.filename = "outputFolder/AMPS_OUTBiomIndx.txt")

    
    
    
    
    # extract the biomass, abundance, waa variables
    atlantis.biomass = outputs$biomass
    #atlantis.abundance = outputs$abundance
    atlantis.meanSizeByAge = outputs$waa
      
##########################################################################################
    # Check if the configuration has run
    # Find a way to return 0 if does not work


##########################################################################################
# Process the outputs so that calibrar like them
    if(length(atlantis.biomass)==2){
      dt.timestep = 2
      output = list(
      MA_biomass = rep(0,dt.timestep), 
      SG_biomass = rep(0,dt.timestep), 
      ZS_biomass = rep(0,dt.timestep), 
      ZM_biomass = rep(0,dt.timestep), 
      ZL_biomass = rep(0,dt.timestep), 
      ZG_biomass = rep(0,dt.timestep), 
      AUR_biomass = rep(0,dt.timestep), 
      SQX_biomass = rep(0,dt.timestep), 
      BMD_biomass = rep(0,dt.timestep), 
      BD_biomass = rep(0,dt.timestep), 
      BG_biomass = rep(0,dt.timestep), 
      BMS_biomass = rep(0,dt.timestep), 
      DUN_biomass = rep(0,dt.timestep), 
      BML_biomass = rep(0,dt.timestep), 
      PWN_biomass = rep(0,dt.timestep), 
      BFF_biomass = rep(0,dt.timestep), 
      BIV_biomass = rep(0,dt.timestep), 
      GEC_biomass = rep(0,dt.timestep), 
      BC_biomass = rep(0,dt.timestep), 
      HEP_biomass = rep(0,dt.timestep), 
      HEC_biomass = rep(0,dt.timestep), 
      FPS_biomass = rep(0,dt.timestep), 
      POP_biomass = rep(0,dt.timestep), 
      CHY_biomass = rep(0,dt.timestep), 
      CHS_biomass = rep(0,dt.timestep), 
      CSY_biomass = rep(0,dt.timestep), 
      CSS_biomass = rep(0,dt.timestep), 
      CSN_biomass = rep(0,dt.timestep), 
      CDS_biomass = rep(0,dt.timestep), 
      CNY_biomass = rep(0,dt.timestep), 
      CNS_biomass = rep(0,dt.timestep), 
      CHC_biomass = rep(0,dt.timestep), 
      CYE_biomass = rep(0,dt.timestep), 
      CKS_biomass = rep(0,dt.timestep), 
      CRH_biomass = rep(0,dt.timestep), 
      CRW_biomass = rep(0,dt.timestep), 
      CRC_biomass = rep(0,dt.timestep), 
      COH_biomass = rep(0,dt.timestep), 
      COS_biomass = rep(0,dt.timestep), 
      COD_biomass = rep(0,dt.timestep), 
      COY_biomass = rep(0,dt.timestep), 
      COR_biomass = rep(0,dt.timestep), 
      CDR_biomass = rep(0,dt.timestep), 
      CMS_biomass = rep(0,dt.timestep), 
      CMF_biomass = rep(0,dt.timestep), 
      CMH_biomass = rep(0,dt.timestep), 
      PIS_biomass = rep(0,dt.timestep), 
      SAL_biomass = rep(0,dt.timestep), 
      SAF_biomass = rep(0,dt.timestep), 
      FMM_biomass = rep(0,dt.timestep), 
      FVS_biomass = rep(0,dt.timestep), 
      ROC_biomass = rep(0,dt.timestep), 
      MRO_biomass = rep(0,dt.timestep), 
      DVR_biomass = rep(0,dt.timestep), 
      MVR_biomass = rep(0,dt.timestep), 
      SMD_biomass = rep(0,dt.timestep), 
      FDF_biomass = rep(0,dt.timestep), 
      HAP_biomass = rep(0,dt.timestep), 
      DOG_biomass = rep(0,dt.timestep), 
      SBL_biomass = rep(0,dt.timestep), 
      SSK_biomass = rep(0,dt.timestep), 
      RAT_biomass = rep(0,dt.timestep), 
      SB_biomass = rep(0,dt.timestep), 
      SP_biomass = rep(0,dt.timestep), 
      BE_biomass = rep(0,dt.timestep), 
      HSL_biomass = rep(0,dt.timestep), 
      CSL_biomass = rep(0,dt.timestep), 
      PIN_biomass = rep(0,dt.timestep), 
      PHR_biomass = rep(0,dt.timestep), 
      ROR_biomass = rep(0,dt.timestep), 
      TOR_biomass = rep(0,dt.timestep), 
      HUW_biomass = rep(0,dt.timestep), 
      
      California_sea_lion1_w = rep(0,dt.timestep), 
      California_sea_lion10_w = rep(0,dt.timestep), 
      California_sea_lion2_w = rep(0,dt.timestep), 
      California_sea_lion3_w = rep(0,dt.timestep), 
      California_sea_lion4_w = rep(0,dt.timestep), 
      California_sea_lion5_w = rep(0,dt.timestep), 
      California_sea_lion6_w = rep(0,dt.timestep), 
      California_sea_lion7_w = rep(0,dt.timestep), 
      California_sea_lion8_w = rep(0,dt.timestep), 
      California_sea_lion9_w = rep(0,dt.timestep), 
      ChinookDSY_Fish1_w = rep(0,dt.timestep), 
      ChinookDSY_Fish2_w = rep(0,dt.timestep), 
      ChinookDSY_Fish3_w = rep(0,dt.timestep), 
      ChinookDSY_Fish4_w = rep(0,dt.timestep), 
      ChinookDSY_Fish5_w = rep(0,dt.timestep), 
      ChinookHY_Fish1_w = rep(0,dt.timestep), 
      ChinookHY_Fish2_w = rep(0,dt.timestep), 
      ChinookHY_Fish3_w = rep(0,dt.timestep), 
      ChinookHY_Fish4_w = rep(0,dt.timestep), 
      ChinookHY_Fish5_w = rep(0,dt.timestep), 
      ChinookNSY_Fish1_w = rep(0,dt.timestep), 
      ChinookNSY_Fish2_w = rep(0,dt.timestep), 
      ChinookNSY_Fish3_w = rep(0,dt.timestep), 
      ChinookNSY_Fish4_w = rep(0,dt.timestep), 
      ChinookNSY_Fish5_w = rep(0,dt.timestep), 
      ChinookNY_Fish1_w = rep(0,dt.timestep), 
      ChinookNY_Fish2_w = rep(0,dt.timestep), 
      ChinookNY_Fish3_w = rep(0,dt.timestep), 
      ChinookNY_Fish4_w = rep(0,dt.timestep), 
      ChinookNY_Fish5_w = rep(0,dt.timestep), 
      ChinookOSY_Fish1_w = rep(0,dt.timestep), 
      ChinookOSY_Fish2_w = rep(0,dt.timestep), 
      ChinookOSY_Fish3_w = rep(0,dt.timestep), 
      ChinookOSY_Fish4_w = rep(0,dt.timestep), 
      ChinookOSY_Fish5_w = rep(0,dt.timestep), 
      ChinookOY_Fish1_w = rep(0,dt.timestep), 
      ChinookOY_Fish2_w = rep(0,dt.timestep), 
      ChinookOY_Fish3_w = rep(0,dt.timestep), 
      ChinookOY_Fish4_w = rep(0,dt.timestep), 
      ChinookOY_Fish5_w = rep(0,dt.timestep), 
      ChinookResH_Fish1_w = rep(0,dt.timestep), 
      ChinookResH_Fish2_w = rep(0,dt.timestep), 
      ChinookResH_Fish3_w = rep(0,dt.timestep), 
      ChinookResH_Fish4_w = rep(0,dt.timestep), 
      ChinookResH_Fish5_w = rep(0,dt.timestep), 
      ChinookResN_Fish1_w = rep(0,dt.timestep), 
      ChinookResN_Fish2_w = rep(0,dt.timestep), 
      ChinookResN_Fish3_w = rep(0,dt.timestep), 
      ChinookResN_Fish4_w = rep(0,dt.timestep), 
      ChinookResN_Fish5_w = rep(0,dt.timestep), 
      ChinookResW_Fish1_w = rep(0,dt.timestep), 
      ChinookResW_Fish2_w = rep(0,dt.timestep), 
      ChinookResW_Fish3_w = rep(0,dt.timestep), 
      ChinookResW_Fish4_w = rep(0,dt.timestep), 
      ChinookResW_Fish5_w = rep(0,dt.timestep), 
      ChinookSKSY_Fish1_w = rep(0,dt.timestep), 
      ChinookSKSY_Fish2_w = rep(0,dt.timestep), 
      ChinookSKSY_Fish3_w = rep(0,dt.timestep), 
      ChinookSKSY_Fish4_w = rep(0,dt.timestep), 
      ChinookSKSY_Fish5_w = rep(0,dt.timestep), 
      ChinookSKY_Fish1_w = rep(0,dt.timestep), 
      ChinookSKY_Fish2_w = rep(0,dt.timestep), 
      ChinookSKY_Fish3_w = rep(0,dt.timestep), 
      ChinookSKY_Fish4_w = rep(0,dt.timestep), 
      ChinookSKY_Fish5_w = rep(0,dt.timestep), 
      ChinookSSY_Fish1_w = rep(0,dt.timestep), 
      ChinookSSY_Fish2_w = rep(0,dt.timestep), 
      ChinookSSY_Fish3_w = rep(0,dt.timestep), 
      ChinookSSY_Fish4_w = rep(0,dt.timestep), 
      ChinookSSY_Fish5_w = rep(0,dt.timestep), 
      ChinookSY_Fish1_w = rep(0,dt.timestep), 
      ChinookSY_Fish2_w = rep(0,dt.timestep), 
      ChinookSY_Fish3_w = rep(0,dt.timestep), 
      ChinookSY_Fish4_w = rep(0,dt.timestep), 
      ChinookSY_Fish5_w = rep(0,dt.timestep), 
      ChinookY_Fish1_w = rep(0,dt.timestep), 
      ChinookY_Fish2_w = rep(0,dt.timestep), 
      ChinookY_Fish3_w = rep(0,dt.timestep), 
      ChinookY_Fish4_w = rep(0,dt.timestep), 
      ChinookY_Fish5_w = rep(0,dt.timestep), 
      ChumFSY_Fish1_w = rep(0,dt.timestep), 
      ChumFSY_Fish2_w = rep(0,dt.timestep), 
      ChumFSY_Fish3_w = rep(0,dt.timestep), 
      ChumFSY_Fish4_w = rep(0,dt.timestep), 
      ChumFSY_Fish5_w = rep(0,dt.timestep), 
      ChumHCSY_Fish1_w = rep(0,dt.timestep), 
      ChumHCSY_Fish2_w = rep(0,dt.timestep), 
      ChumHCSY_Fish3_w = rep(0,dt.timestep), 
      ChumHCSY_Fish4_w = rep(0,dt.timestep), 
      ChumHCSY_Fish5_w = rep(0,dt.timestep), 
      ChumHSY_Fish1_w = rep(0,dt.timestep), 
      ChumHSY_Fish2_w = rep(0,dt.timestep), 
      ChumHSY_Fish3_w = rep(0,dt.timestep), 
      ChumHSY_Fish4_w = rep(0,dt.timestep), 
      ChumHSY_Fish5_w = rep(0,dt.timestep), 
      CohoDSY_Fish1_w = rep(0,dt.timestep), 
      CohoDSY_Fish2_w = rep(0,dt.timestep), 
      CohoDSY_Fish3_w = rep(0,dt.timestep), 
      CohoHY_Fish1_w = rep(0,dt.timestep), 
      CohoHY_Fish2_w = rep(0,dt.timestep), 
      CohoHY_Fish3_w = rep(0,dt.timestep), 
      CohoOY_Fish1_w = rep(0,dt.timestep), 
      CohoOY_Fish2_w = rep(0,dt.timestep), 
      CohoOY_Fish3_w = rep(0,dt.timestep), 
      CohoRes_Fish1_w = rep(0,dt.timestep), 
      CohoRes_Fish2_w = rep(0,dt.timestep), 
      CohoRes_Fish3_w = rep(0,dt.timestep), 
      CohoResD_Fish1_w = rep(0,dt.timestep), 
      CohoResD_Fish2_w = rep(0,dt.timestep), 
      CohoResD_Fish3_w = rep(0,dt.timestep), 
      CohoSY_Fish1_w = rep(0,dt.timestep), 
      CohoSY_Fish2_w = rep(0,dt.timestep), 
      CohoSY_Fish3_w = rep(0,dt.timestep), 
      DemRock_Fish1_w = rep(0,dt.timestep), 
      DemRock_Fish10_w = rep(0,dt.timestep), 
      DemRock_Fish2_w = rep(0,dt.timestep), 
      DemRock_Fish3_w = rep(0,dt.timestep), 
      DemRock_Fish4_w = rep(0,dt.timestep), 
      DemRock_Fish5_w = rep(0,dt.timestep), 
      DemRock_Fish6_w = rep(0,dt.timestep), 
      DemRock_Fish7_w = rep(0,dt.timestep), 
      DemRock_Fish8_w = rep(0,dt.timestep), 
      DemRock_Fish9_w = rep(0,dt.timestep), 
      DemVRock_Fish1_w = rep(0,dt.timestep), 
      DemVRock_Fish10_w = rep(0,dt.timestep), 
      DemVRock_Fish2_w = rep(0,dt.timestep), 
      DemVRock_Fish3_w = rep(0,dt.timestep), 
      DemVRock_Fish4_w = rep(0,dt.timestep), 
      DemVRock_Fish5_w = rep(0,dt.timestep), 
      DemVRock_Fish6_w = rep(0,dt.timestep), 
      DemVRock_Fish7_w = rep(0,dt.timestep), 
      DemVRock_Fish8_w = rep(0,dt.timestep), 
      DemVRock_Fish9_w = rep(0,dt.timestep), 
      Gadiods_Fish1_w = rep(0,dt.timestep), 
      Gadiods_Fish10_w = rep(0,dt.timestep), 
      Gadiods_Fish2_w = rep(0,dt.timestep), 
      Gadiods_Fish3_w = rep(0,dt.timestep), 
      Gadiods_Fish4_w = rep(0,dt.timestep), 
      Gadiods_Fish5_w = rep(0,dt.timestep), 
      Gadiods_Fish6_w = rep(0,dt.timestep), 
      Gadiods_Fish7_w = rep(0,dt.timestep), 
      Gadiods_Fish8_w = rep(0,dt.timestep), 
      Gadiods_Fish9_w = rep(0,dt.timestep), 
      Harbor_seal1_w = rep(0,dt.timestep), 
      Harbor_seal10_w = rep(0,dt.timestep), 
      Harbor_seal2_w = rep(0,dt.timestep), 
      Harbor_seal3_w = rep(0,dt.timestep), 
      Harbor_seal4_w = rep(0,dt.timestep), 
      Harbor_seal5_w = rep(0,dt.timestep), 
      Harbor_seal6_w = rep(0,dt.timestep), 
      Harbor_seal7_w = rep(0,dt.timestep), 
      Harbor_seal8_w = rep(0,dt.timestep), 
      Harbor_seal9_w = rep(0,dt.timestep), 
      Herring_Cherry1_w = rep(0,dt.timestep), 
      Herring_Cherry2_w = rep(0,dt.timestep), 
      Herring_Cherry3_w = rep(0,dt.timestep), 
      Herring_Cherry4_w = rep(0,dt.timestep), 
      Herring_Cherry5_w = rep(0,dt.timestep), 
      Herring_Cherry6_w = rep(0,dt.timestep), 
      Herring_PS1_w = rep(0,dt.timestep), 
      Herring_PS2_w = rep(0,dt.timestep), 
      Herring_PS3_w = rep(0,dt.timestep), 
      Herring_PS4_w = rep(0,dt.timestep), 
      Herring_PS5_w = rep(0,dt.timestep), 
      Herring_PS6_w = rep(0,dt.timestep), 
      Herring_PS7_w = rep(0,dt.timestep), 
      Hump_whale1_w = rep(0,dt.timestep), 
      Hump_whale10_w = rep(0,dt.timestep), 
      Hump_whale2_w = rep(0,dt.timestep), 
      Hump_whale3_w = rep(0,dt.timestep), 
      Hump_whale4_w = rep(0,dt.timestep), 
      Hump_whale5_w = rep(0,dt.timestep), 
      Hump_whale6_w = rep(0,dt.timestep), 
      Hump_whale7_w = rep(0,dt.timestep), 
      Hump_whale8_w = rep(0,dt.timestep), 
      Hump_whale9_w = rep(0,dt.timestep), 
      LgDem_Fish1_w = rep(0,dt.timestep), 
      LgDem_Fish10_w = rep(0,dt.timestep), 
      LgDem_Fish2_w = rep(0,dt.timestep), 
      LgDem_Fish3_w = rep(0,dt.timestep), 
      LgDem_Fish4_w = rep(0,dt.timestep), 
      LgDem_Fish5_w = rep(0,dt.timestep), 
      LgDem_Fish6_w = rep(0,dt.timestep), 
      LgDem_Fish7_w = rep(0,dt.timestep), 
      LgDem_Fish8_w = rep(0,dt.timestep), 
      LgDem_Fish9_w = rep(0,dt.timestep), 
      MidRock_Fish1_w = rep(0,dt.timestep), 
      MidRock_Fish10_w = rep(0,dt.timestep), 
      MidRock_Fish2_w = rep(0,dt.timestep), 
      MidRock_Fish3_w = rep(0,dt.timestep), 
      MidRock_Fish4_w = rep(0,dt.timestep), 
      MidRock_Fish5_w = rep(0,dt.timestep), 
      MidRock_Fish6_w = rep(0,dt.timestep), 
      MidRock_Fish7_w = rep(0,dt.timestep), 
      MidRock_Fish8_w = rep(0,dt.timestep), 
      MidRock_Fish9_w = rep(0,dt.timestep), 
      MidVRock_Fish1_w = rep(0,dt.timestep), 
      MidVRock_Fish10_w = rep(0,dt.timestep), 
      MidVRock_Fish2_w = rep(0,dt.timestep), 
      MidVRock_Fish3_w = rep(0,dt.timestep), 
      MidVRock_Fish4_w = rep(0,dt.timestep), 
      MidVRock_Fish5_w = rep(0,dt.timestep), 
      MidVRock_Fish6_w = rep(0,dt.timestep), 
      MidVRock_Fish7_w = rep(0,dt.timestep), 
      MidVRock_Fish8_w = rep(0,dt.timestep), 
      MidVRock_Fish9_w = rep(0,dt.timestep), 
      NonPisc_Seabird1_w = rep(0,dt.timestep), 
      NonPisc_Seabird10_w = rep(0,dt.timestep), 
      NonPisc_Seabird2_w = rep(0,dt.timestep), 
      NonPisc_Seabird3_w = rep(0,dt.timestep), 
      NonPisc_Seabird4_w = rep(0,dt.timestep), 
      NonPisc_Seabird5_w = rep(0,dt.timestep), 
      NonPisc_Seabird6_w = rep(0,dt.timestep), 
      NonPisc_Seabird7_w = rep(0,dt.timestep), 
      NonPisc_Seabird8_w = rep(0,dt.timestep), 
      NonPisc_Seabird9_w = rep(0,dt.timestep), 
      OtherSal_Fish1_w = rep(0,dt.timestep), 
      OtherSal_Fish2_w = rep(0,dt.timestep), 
      OtherSal_Fish3_w = rep(0,dt.timestep), 
      OtherSal_Fish4_w = rep(0,dt.timestep), 
      OtherSal_Fish5_w = rep(0,dt.timestep), 
      OtherSal_Fish6_w = rep(0,dt.timestep), 
      OtherSal_Fish7_w = rep(0,dt.timestep), 
      OtherSal_Fish8_w = rep(0,dt.timestep), 
      Perch_Fish1_w = rep(0,dt.timestep), 
      Perch_Fish2_w = rep(0,dt.timestep), 
      Perch_Fish3_w = rep(0,dt.timestep), 
      Perch_Fish4_w = rep(0,dt.timestep), 
      Perch_Fish5_w = rep(0,dt.timestep), 
      Perch_Fish6_w = rep(0,dt.timestep), 
      Perch_Fish7_w = rep(0,dt.timestep), 
      Perch_Fish8_w = rep(0,dt.timestep), 
      PinkSY_Fish1_w = rep(0,dt.timestep), 
      PinkSY_Fish2_w = rep(0,dt.timestep), 
      PinkSY_Fish3_w = rep(0,dt.timestep), 
      Pinniped1_w = rep(0,dt.timestep), 
      Pinniped10_w = rep(0,dt.timestep), 
      Pinniped2_w = rep(0,dt.timestep), 
      Pinniped3_w = rep(0,dt.timestep), 
      Pinniped4_w = rep(0,dt.timestep), 
      Pinniped5_w = rep(0,dt.timestep), 
      Pinniped6_w = rep(0,dt.timestep), 
      Pinniped7_w = rep(0,dt.timestep), 
      Pinniped8_w = rep(0,dt.timestep), 
      Pinniped9_w = rep(0,dt.timestep), 
      Pisc_Seabird1_w = rep(0,dt.timestep), 
      Pisc_Seabird10_w = rep(0,dt.timestep), 
      Pisc_Seabird2_w = rep(0,dt.timestep), 
      Pisc_Seabird3_w = rep(0,dt.timestep), 
      Pisc_Seabird4_w = rep(0,dt.timestep), 
      Pisc_Seabird5_w = rep(0,dt.timestep), 
      Pisc_Seabird6_w = rep(0,dt.timestep), 
      Pisc_Seabird7_w = rep(0,dt.timestep), 
      Pisc_Seabird8_w = rep(0,dt.timestep), 
      Pisc_Seabird9_w = rep(0,dt.timestep), 
      PiscFlat_Fish1_w = rep(0,dt.timestep), 
      PiscFlat_Fish10_w = rep(0,dt.timestep), 
      PiscFlat_Fish2_w = rep(0,dt.timestep), 
      PiscFlat_Fish3_w = rep(0,dt.timestep), 
      PiscFlat_Fish4_w = rep(0,dt.timestep), 
      PiscFlat_Fish5_w = rep(0,dt.timestep), 
      PiscFlat_Fish6_w = rep(0,dt.timestep), 
      PiscFlat_Fish7_w = rep(0,dt.timestep), 
      PiscFlat_Fish8_w = rep(0,dt.timestep), 
      PiscFlat_Fish9_w = rep(0,dt.timestep), 
      Porpoise1_w = rep(0,dt.timestep), 
      Porpoise10_w = rep(0,dt.timestep), 
      Porpoise2_w = rep(0,dt.timestep), 
      Porpoise3_w = rep(0,dt.timestep), 
      Porpoise4_w = rep(0,dt.timestep), 
      Porpoise5_w = rep(0,dt.timestep), 
      Porpoise6_w = rep(0,dt.timestep), 
      Porpoise7_w = rep(0,dt.timestep), 
      Porpoise8_w = rep(0,dt.timestep), 
      Porpoise9_w = rep(0,dt.timestep), 
      Raptors1_w = rep(0,dt.timestep), 
      Raptors10_w = rep(0,dt.timestep), 
      Raptors2_w = rep(0,dt.timestep), 
      Raptors3_w = rep(0,dt.timestep), 
      Raptors4_w = rep(0,dt.timestep), 
      Raptors5_w = rep(0,dt.timestep), 
      Raptors6_w = rep(0,dt.timestep), 
      Raptors7_w = rep(0,dt.timestep), 
      Raptors8_w = rep(0,dt.timestep), 
      Raptors9_w = rep(0,dt.timestep), 
      Ratfish1_w = rep(0,dt.timestep), 
      Ratfish10_w = rep(0,dt.timestep), 
      Ratfish2_w = rep(0,dt.timestep), 
      Ratfish3_w = rep(0,dt.timestep), 
      Ratfish4_w = rep(0,dt.timestep), 
      Ratfish5_w = rep(0,dt.timestep), 
      Ratfish6_w = rep(0,dt.timestep), 
      Ratfish7_w = rep(0,dt.timestep), 
      Ratfish8_w = rep(0,dt.timestep), 
      Ratfish9_w = rep(0,dt.timestep), 
      Res_Orca1_w = rep(0,dt.timestep), 
      Res_Orca10_w = rep(0,dt.timestep), 
      Res_Orca2_w = rep(0,dt.timestep), 
      Res_Orca3_w = rep(0,dt.timestep), 
      Res_Orca4_w = rep(0,dt.timestep), 
      Res_Orca5_w = rep(0,dt.timestep), 
      Res_Orca6_w = rep(0,dt.timestep), 
      Res_Orca7_w = rep(0,dt.timestep), 
      Res_Orca8_w = rep(0,dt.timestep), 
      Res_Orca9_w = rep(0,dt.timestep), 
      SGeorgia_Fish1_w = rep(0,dt.timestep), 
      SGeorgia_Fish2_w = rep(0,dt.timestep), 
      SGeorgia_Fish3_w = rep(0,dt.timestep), 
      SGeorgia_Fish4_w = rep(0,dt.timestep), 
      SGeorgia_Fish5_w = rep(0,dt.timestep), 
      Sixgill_Shark1_w = rep(0,dt.timestep), 
      Sixgill_Shark10_w = rep(0,dt.timestep), 
      Sixgill_Shark2_w = rep(0,dt.timestep), 
      Sixgill_Shark3_w = rep(0,dt.timestep), 
      Sixgill_Shark4_w = rep(0,dt.timestep), 
      Sixgill_Shark5_w = rep(0,dt.timestep), 
      Sixgill_Shark6_w = rep(0,dt.timestep), 
      Sixgill_Shark7_w = rep(0,dt.timestep), 
      Sixgill_Shark8_w = rep(0,dt.timestep), 
      Sixgill_Shark9_w = rep(0,dt.timestep), 
      SkateRay1_w = rep(0,dt.timestep), 
      SkateRay10_w = rep(0,dt.timestep), 
      SkateRay2_w = rep(0,dt.timestep), 
      SkateRay3_w = rep(0,dt.timestep), 
      SkateRay4_w = rep(0,dt.timestep), 
      SkateRay5_w = rep(0,dt.timestep), 
      SkateRay6_w = rep(0,dt.timestep), 
      SkateRay7_w = rep(0,dt.timestep), 
      SkateRay8_w = rep(0,dt.timestep), 
      SkateRay9_w = rep(0,dt.timestep), 
      Sm_Plank_Fish1_w = rep(0,dt.timestep), 
      Sm_Plank_Fish2_w = rep(0,dt.timestep), 
      Sm_Plank_Fish3_w = rep(0,dt.timestep), 
      Sm_Plank_Fish4_w = rep(0,dt.timestep), 
      Sm_Plank_Fish5_w = rep(0,dt.timestep), 
      Sm_Plank_Fish6_w = rep(0,dt.timestep), 
      Sm_Plank_Fish7_w = rep(0,dt.timestep), 
      Sm_Plank_Fish8_w = rep(0,dt.timestep), 
      SmDem_Fish1_w = rep(0,dt.timestep), 
      SmDem_Fish2_w = rep(0,dt.timestep), 
      SmDem_Fish3_w = rep(0,dt.timestep), 
      SmDem_Fish4_w = rep(0,dt.timestep), 
      SmDem_Fish5_w = rep(0,dt.timestep), 
      SmFlat_Fish1_w = rep(0,dt.timestep), 
      SmFlat_Fish10_w = rep(0,dt.timestep), 
      SmFlat_Fish2_w = rep(0,dt.timestep), 
      SmFlat_Fish3_w = rep(0,dt.timestep), 
      SmFlat_Fish4_w = rep(0,dt.timestep), 
      SmFlat_Fish5_w = rep(0,dt.timestep), 
      SmFlat_Fish6_w = rep(0,dt.timestep), 
      SmFlat_Fish7_w = rep(0,dt.timestep), 
      SmFlat_Fish8_w = rep(0,dt.timestep), 
      SmFlat_Fish9_w = rep(0,dt.timestep), 
      Spinydog_Fish1_w = rep(0,dt.timestep), 
      Spinydog_Fish10_w = rep(0,dt.timestep), 
      Spinydog_Fish2_w = rep(0,dt.timestep), 
      Spinydog_Fish3_w = rep(0,dt.timestep), 
      Spinydog_Fish4_w = rep(0,dt.timestep), 
      Spinydog_Fish5_w = rep(0,dt.timestep), 
      Spinydog_Fish6_w = rep(0,dt.timestep), 
      Spinydog_Fish7_w = rep(0,dt.timestep), 
      Spinydog_Fish8_w = rep(0,dt.timestep), 
      Spinydog_Fish9_w = rep(0,dt.timestep), 
      Trans_Orca1_w = rep(0,dt.timestep), 
      Trans_Orca10_w = rep(0,dt.timestep), 
      Trans_Orca2_w = rep(0,dt.timestep), 
      Trans_Orca3_w = rep(0,dt.timestep), 
      Trans_Orca4_w = rep(0,dt.timestep), 
      Trans_Orca5_w = rep(0,dt.timestep), 
      Trans_Orca6_w = rep(0,dt.timestep), 
      Trans_Orca7_w = rep(0,dt.timestep), 
      Trans_Orca8_w = rep(0,dt.timestep), 
      Trans_Orca9_w = rep(0,dt.timestep))

    }else{
output = list(

      # Biomass
      MA_biomass = unname(unlist(atlantis.biomass["Macroalgae"])), 
      SG_biomass = unname(unlist(atlantis.biomass["Seagrass"])), 
      ZS_biomass = unname(unlist(atlantis.biomass["Micro_Zoo"])), 
      ZM_biomass = unname(unlist(atlantis.biomass["Meso_Zoo"])), 
      ZL_biomass = unname(unlist(atlantis.biomass["Lrg_Zoo"])), 
      ZG_biomass = unname(unlist(atlantis.biomass["Gel_Zoo"])), 
      AUR_biomass = unname(unlist(atlantis.biomass["Aurelia"])), 
      SQX_biomass = unname(unlist(atlantis.biomass["Squid"])), 
      BMD_biomass = unname(unlist(atlantis.biomass["Macrobenth_Deep"])), 
      BD_biomass = unname(unlist(atlantis.biomass["Deposit_Feeder"])), 
      BG_biomass = unname(unlist(atlantis.biomass["Benthic_grazer"])), 
      BMS_biomass = unname(unlist(atlantis.biomass["Octopi"])), 
      DUN_biomass = unname(unlist(atlantis.biomass["Dungeness"])), 
      BML_biomass = unname(unlist(atlantis.biomass["Crab"])), 
      PWN_biomass = unname(unlist(atlantis.biomass["Shrimp"])), 
      BFF_biomass = unname(unlist(atlantis.biomass["Filter_Other"])), 
      BIV_biomass = unname(unlist(atlantis.biomass["Bivalve"])), 
      GEC_biomass = unname(unlist(atlantis.biomass["Geoduck"])), 
      BC_biomass = unname(unlist(atlantis.biomass["Carn_Infauna"])), 
      HEP_biomass = unname(unlist(atlantis.biomass["Herring_PS"])), 
      HEC_biomass = unname(unlist(atlantis.biomass["Herring_Cherry"])), 
      FPS_biomass = unname(unlist(atlantis.biomass["Sm_Plank_Fish"])), 
      POP_biomass = unname(unlist(atlantis.biomass["Perch_Fish"])), 
      CHY_biomass = unname(unlist(atlantis.biomass["ChinookY_Fish"])), 
      CHS_biomass = unname(unlist(atlantis.biomass["ChinookSY_Fish"])), 
      CSY_biomass = unname(unlist(atlantis.biomass["ChinookSKY_Fish"])), 
      CSS_biomass = unname(unlist(atlantis.biomass["ChinookSKSY_Fish"])), 
      CSN_biomass = unname(unlist(atlantis.biomass["ChinookSSY_Fish"])), 
      CDS_biomass = unname(unlist(atlantis.biomass["ChinookDSY_Fish"])), 
      CNY_biomass = unname(unlist(atlantis.biomass["ChinookNY_Fish"])), 
      CNS_biomass = unname(unlist(atlantis.biomass["ChinookNSY_Fish"])), 
      CHC_biomass = unname(unlist(atlantis.biomass["ChinookHY_Fish"])), 
      CYE_biomass = unname(unlist(atlantis.biomass["ChinookOY_Fish"])), 
      CKS_biomass = unname(unlist(atlantis.biomass["ChinookOSY_Fish"])), 
      CRH_biomass = unname(unlist(atlantis.biomass["ChinookResH_Fish"])), 
      CRW_biomass = unname(unlist(atlantis.biomass["ChinookResN_Fish"])), 
      CRC_biomass = unname(unlist(atlantis.biomass["ChinookResW_Fish"])), 
      COH_biomass = unname(unlist(atlantis.biomass["CohoHY_Fish"])), 
      COS_biomass = unname(unlist(atlantis.biomass["CohoSY_Fish"])), 
      COD_biomass = unname(unlist(atlantis.biomass["CohoDSY_Fish"])), 
      COY_biomass = unname(unlist(atlantis.biomass["CohoOY_Fish"])), 
      COR_biomass = unname(unlist(atlantis.biomass["CohoRes_Fish"])), 
      CDR_biomass = unname(unlist(atlantis.biomass["CohoResD_Fish"])), 
      CMS_biomass = unname(unlist(atlantis.biomass["ChumHSY_Fish"])), 
      CMF_biomass = unname(unlist(atlantis.biomass["ChumFSY_Fish"])), 
      CMH_biomass = unname(unlist(atlantis.biomass["ChumHCSY_Fish"])), 
      PIS_biomass = unname(unlist(atlantis.biomass["PinkSY_Fish"])), 
      SAL_biomass = unname(unlist(atlantis.biomass["OtherSal_Fish"])), 
      SAF_biomass = unname(unlist(atlantis.biomass["SGeorgia_Fish"])), 
      FMM_biomass = unname(unlist(atlantis.biomass["Gadiods_Fish"])), 
      FVS_biomass = unname(unlist(atlantis.biomass["LgDem_Fish"])), 
      ROC_biomass = unname(unlist(atlantis.biomass["DemRock_Fish"])), 
      MRO_biomass = unname(unlist(atlantis.biomass["MidRock_Fish"])), 
      DVR_biomass = unname(unlist(atlantis.biomass["DemVRock_Fish"])), 
      MVR_biomass = unname(unlist(atlantis.biomass["MidVRock_Fish"])), 
      SMD_biomass = unname(unlist(atlantis.biomass["SmDem_Fish"])), 
      FDF_biomass = unname(unlist(atlantis.biomass["SmFlat_Fish"])), 
      HAP_biomass = unname(unlist(atlantis.biomass["PiscFlat_Fish"])), 
      DOG_biomass = unname(unlist(atlantis.biomass["Spinydog_Fish"])), 
      SBL_biomass = unname(unlist(atlantis.biomass["Sixgill_Shark"])), 
      SSK_biomass = unname(unlist(atlantis.biomass["SkateRay"])), 
      RAT_biomass = unname(unlist(atlantis.biomass["Ratfish"])), 
      SB_biomass = unname(unlist(atlantis.biomass["Pisc_Seabird"])), 
      SP_biomass = unname(unlist(atlantis.biomass["NonPisc_Seabird"])), 
      BE_biomass = unname(unlist(atlantis.biomass["Raptors"])), 
      HSL_biomass = unname(unlist(atlantis.biomass["Harbor_seal"])), 
      CSL_biomass = unname(unlist(atlantis.biomass["California_sea_lion"])), 
      PIN_biomass = unname(unlist(atlantis.biomass["Pinniped"])), 
      PHR_biomass = unname(unlist(atlantis.biomass["Porpoise"])), 
      ROR_biomass = unname(unlist(atlantis.biomass["Res_Orca"])), 
      TOR_biomass = unname(unlist(atlantis.biomass["Trans_Orca"])), 
      HUW_biomass = unname(unlist(atlantis.biomass["Hump_whale"])), 
      
      
      # WAA
      California_sea_lion1_w = unname(unlist(atlantis.meanSizeByAge["California_sea_lion1"])), 
      California_sea_lion10_w = unname(unlist(atlantis.meanSizeByAge["California_sea_lion10"])),
      California_sea_lion2_w = unname(unlist(atlantis.meanSizeByAge["California_sea_lion2"])),
      California_sea_lion3_w = unname(unlist(atlantis.meanSizeByAge["California_sea_lion3"])),
      California_sea_lion4_w = unname(unlist(atlantis.meanSizeByAge["California_sea_lion4"])),
      California_sea_lion5_w = unname(unlist(atlantis.meanSizeByAge["California_sea_lion5"])),
      California_sea_lion6_w = unname(unlist(atlantis.meanSizeByAge["California_sea_lion6"])),
      California_sea_lion7_w = unname(unlist(atlantis.meanSizeByAge["California_sea_lion7"])),
      California_sea_lion8_w = unname(unlist(atlantis.meanSizeByAge["California_sea_lion8"])),
      California_sea_lion9_w = unname(unlist(atlantis.meanSizeByAge["California_sea_lion9"])), 
      
      ChinookDSY_Fish1_w = unname(unlist(atlantis.meanSizeByAge["ChinookDSY_Fish1"])),
      ChinookDSY_Fish2_w = unname(unlist(atlantis.meanSizeByAge["ChinookDSY_Fish2"])),
      ChinookDSY_Fish3_w = unname(unlist(atlantis.meanSizeByAge["ChinookDSY_Fish3"])),
      ChinookDSY_Fish4_w = unname(unlist(atlantis.meanSizeByAge["ChinookDSY_Fish4"])),
      ChinookDSY_Fish5_w = unname(unlist(atlantis.meanSizeByAge["ChinookDSY_Fish5"])), 
      
      ChinookHY_Fish1_w = unname(unlist(atlantis.meanSizeByAge["ChinookHY_Fish1"])),
      ChinookHY_Fish2_w = unname(unlist(atlantis.meanSizeByAge["ChinookHY_Fish2"])),
      ChinookHY_Fish3_w = unname(unlist(atlantis.meanSizeByAge["ChinookHY_Fish3"])),
      ChinookHY_Fish4_w = unname(unlist(atlantis.meanSizeByAge["ChinookHY_Fish4"])),
      ChinookHY_Fish5_w = unname(unlist(atlantis.meanSizeByAge["ChinookHY_Fish5"])), 
      
      ChinookNSY_Fish1_w = unname(unlist(atlantis.meanSizeByAge["ChinookNSY_Fish1"])),
      ChinookNSY_Fish2_w = unname(unlist(atlantis.meanSizeByAge["ChinookNSY_Fish2"])),
      ChinookNSY_Fish3_w = unname(unlist(atlantis.meanSizeByAge["ChinookNSY_Fish3"])),
      ChinookNSY_Fish4_w = unname(unlist(atlantis.meanSizeByAge["ChinookNSY_Fish4"])),
      ChinookNSY_Fish5_w = unname(unlist(atlantis.meanSizeByAge["ChinookNSY_Fish5"])), 
      
      ChinookNY_Fish1_w = unname(unlist(atlantis.meanSizeByAge["ChinookNY_Fish1"])),
      ChinookNY_Fish2_w = unname(unlist(atlantis.meanSizeByAge["ChinookNY_Fish2"])),
      ChinookNY_Fish3_w = unname(unlist(atlantis.meanSizeByAge["ChinookNY_Fish3"])),
      ChinookNY_Fish4_w = unname(unlist(atlantis.meanSizeByAge["ChinookNY_Fish4"])),
      ChinookNY_Fish5_w = unname(unlist(atlantis.meanSizeByAge["ChinookNY_Fish5"])), 
      
      ChinookOSY_Fish1_w = unname(unlist(atlantis.meanSizeByAge["ChinookOSY_Fish1"])),
      ChinookOSY_Fish2_w = unname(unlist(atlantis.meanSizeByAge["ChinookOSY_Fish2"])),
      ChinookOSY_Fish3_w = unname(unlist(atlantis.meanSizeByAge["ChinookOSY_Fish3"])),
      ChinookOSY_Fish4_w = unname(unlist(atlantis.meanSizeByAge["ChinookOSY_Fish4"])),
      ChinookOSY_Fish5_w = unname(unlist(atlantis.meanSizeByAge["ChinookOSY_Fish5"])), 
      
      ChinookOY_Fish1_w = unname(unlist(atlantis.meanSizeByAge["ChinookOY_Fish1"])),
      ChinookOY_Fish2_w = unname(unlist(atlantis.meanSizeByAge["ChinookOY_Fish2"])),
      ChinookOY_Fish3_w = unname(unlist(atlantis.meanSizeByAge["ChinookOY_Fish3"])),
      ChinookOY_Fish4_w = unname(unlist(atlantis.meanSizeByAge["ChinookOY_Fish4"])),
      ChinookOY_Fish5_w = unname(unlist(atlantis.meanSizeByAge["ChinookOY_Fish5"])), 
      
      ChinookResH_Fish1_w = unname(unlist(atlantis.meanSizeByAge["ChinookResH_Fish1"])),
      ChinookResH_Fish2_w = unname(unlist(atlantis.meanSizeByAge["ChinookResH_Fish2"])),
      ChinookResH_Fish3_w = unname(unlist(atlantis.meanSizeByAge["ChinookResH_Fish3"])),
      ChinookResH_Fish4_w = unname(unlist(atlantis.meanSizeByAge["ChinookResH_Fish4"])),
      ChinookResH_Fish5_w = unname(unlist(atlantis.meanSizeByAge["ChinookResH_Fish5"])), 
      
      ChinookResN_Fish1_w = unname(unlist(atlantis.meanSizeByAge["ChinookResN_Fish1"])),
      ChinookResN_Fish2_w = unname(unlist(atlantis.meanSizeByAge["ChinookResN_Fish2"])),
      ChinookResN_Fish3_w = unname(unlist(atlantis.meanSizeByAge["ChinookResN_Fish3"])),
      ChinookResN_Fish4_w = unname(unlist(atlantis.meanSizeByAge["ChinookResN_Fish4"])),
      ChinookResN_Fish5_w = unname(unlist(atlantis.meanSizeByAge["ChinookResN_Fish5"])), 
      
      ChinookResW_Fish1_w = unname(unlist(atlantis.meanSizeByAge["ChinookResW_Fish1"])),
      ChinookResW_Fish2_w = unname(unlist(atlantis.meanSizeByAge["ChinookResW_Fish2"])),
      ChinookResW_Fish3_w = unname(unlist(atlantis.meanSizeByAge["ChinookResW_Fish3"])),
      ChinookResW_Fish4_w = unname(unlist(atlantis.meanSizeByAge["ChinookResW_Fish4"])),
      ChinookResW_Fish5_w = unname(unlist(atlantis.meanSizeByAge["ChinookResW_Fish5"])), 
      
      ChinookSKSY_Fish1_w = unname(unlist(atlantis.meanSizeByAge["ChinookSKSY_Fish1"])),
      ChinookSKSY_Fish2_w = unname(unlist(atlantis.meanSizeByAge["ChinookSKSY_Fish2"])),
      ChinookSKSY_Fish3_w = unname(unlist(atlantis.meanSizeByAge["ChinookSKSY_Fish3"])),
      ChinookSKSY_Fish4_w = unname(unlist(atlantis.meanSizeByAge["ChinookSKSY_Fish4"])),
      ChinookSKSY_Fish5_w = unname(unlist(atlantis.meanSizeByAge["ChinookSKSY_Fish5"])), 
      
      ChinookSKY_Fish1_w = unname(unlist(atlantis.meanSizeByAge["ChinookSKY_Fish1"])),
      ChinookSKY_Fish2_w = unname(unlist(atlantis.meanSizeByAge["ChinookSKY_Fish2"])),
      ChinookSKY_Fish3_w = unname(unlist(atlantis.meanSizeByAge["ChinookSKY_Fish3"])),
      ChinookSKY_Fish4_w = unname(unlist(atlantis.meanSizeByAge["ChinookSKY_Fish4"])),
      ChinookSKY_Fish5_w = unname(unlist(atlantis.meanSizeByAge["ChinookSKY_Fish5"])), 
      
      ChinookSSY_Fish1_w = unname(unlist(atlantis.meanSizeByAge["ChinookSSY_Fish1"])),
      ChinookSSY_Fish2_w = unname(unlist(atlantis.meanSizeByAge["ChinookSSY_Fish2"])),
      ChinookSSY_Fish3_w = unname(unlist(atlantis.meanSizeByAge["ChinookSSY_Fish3"])),
      ChinookSSY_Fish4_w = unname(unlist(atlantis.meanSizeByAge["ChinookSSY_Fish4"])),
      ChinookSSY_Fish5_w = unname(unlist(atlantis.meanSizeByAge["ChinookSSY_Fish5"])), 
      
      ChinookSY_Fish1_w = unname(unlist(atlantis.meanSizeByAge["ChinookSY_Fish1"])),
      ChinookSY_Fish2_w = unname(unlist(atlantis.meanSizeByAge["ChinookSY_Fish2"])),
      ChinookSY_Fish3_w = unname(unlist(atlantis.meanSizeByAge["ChinookSY_Fish3"])),
      ChinookSY_Fish4_w = unname(unlist(atlantis.meanSizeByAge["ChinookSY_Fish4"])),
      ChinookSY_Fish5_w = unname(unlist(atlantis.meanSizeByAge["ChinookSY_Fish5"])), 
      
      ChinookY_Fish1_w = unname(unlist(atlantis.meanSizeByAge["ChinookY_Fish1"])),
      ChinookY_Fish2_w = unname(unlist(atlantis.meanSizeByAge["ChinookY_Fish2"])),
      ChinookY_Fish3_w = unname(unlist(atlantis.meanSizeByAge["ChinookY_Fish3"])),
      ChinookY_Fish4_w = unname(unlist(atlantis.meanSizeByAge["ChinookY_Fish4"])),
      ChinookY_Fish5_w = unname(unlist(atlantis.meanSizeByAge["ChinookY_Fish5"])), 
      
      ChumFSY_Fish1_w = unname(unlist(atlantis.meanSizeByAge["ChumFSY_Fish1"])),
      ChumFSY_Fish2_w = unname(unlist(atlantis.meanSizeByAge["ChumFSY_Fish2"])),
      ChumFSY_Fish3_w = unname(unlist(atlantis.meanSizeByAge["ChumFSY_Fish3"])),
      ChumFSY_Fish4_w = unname(unlist(atlantis.meanSizeByAge["ChumFSY_Fish4"])),
      ChumFSY_Fish5_w = unname(unlist(atlantis.meanSizeByAge["ChumFSY_Fish5"])), 
      
      ChumHCSY_Fish1_w = unname(unlist(atlantis.meanSizeByAge["ChumHCSY_Fish1"])),
      ChumHCSY_Fish2_w = unname(unlist(atlantis.meanSizeByAge["ChumHCSY_Fish2"])),
      ChumHCSY_Fish3_w = unname(unlist(atlantis.meanSizeByAge["ChumHCSY_Fish3"])),
      ChumHCSY_Fish4_w = unname(unlist(atlantis.meanSizeByAge["ChumHCSY_Fish4"])),
      ChumHCSY_Fish5_w = unname(unlist(atlantis.meanSizeByAge["ChumHCSY_Fish5"])), 
      
      ChumHSY_Fish1_w = unname(unlist(atlantis.meanSizeByAge["ChumHSY_Fish1"])),
      ChumHSY_Fish2_w = unname(unlist(atlantis.meanSizeByAge["ChumHSY_Fish2"])),
      ChumHSY_Fish3_w = unname(unlist(atlantis.meanSizeByAge["ChumHSY_Fish3"])),
      ChumHSY_Fish4_w = unname(unlist(atlantis.meanSizeByAge["ChumHSY_Fish4"])),
      ChumHSY_Fish5_w = unname(unlist(atlantis.meanSizeByAge["ChumHSY_Fish5"])), 
      
      CohoDSY_Fish1_w = unname(unlist(atlantis.meanSizeByAge["CohoDSY_Fish1"])),
      CohoDSY_Fish2_w = unname(unlist(atlantis.meanSizeByAge["CohoDSY_Fish2"])),
      CohoDSY_Fish3_w = unname(unlist(atlantis.meanSizeByAge["CohoDSY_Fish3"])), 
      
      CohoHY_Fish1_w = unname(unlist(atlantis.meanSizeByAge["CohoHY_Fish1"])),
      CohoHY_Fish2_w = unname(unlist(atlantis.meanSizeByAge["CohoHY_Fish2"])),
      CohoHY_Fish3_w = unname(unlist(atlantis.meanSizeByAge["CohoHY_Fish3"])), 
      
      CohoOY_Fish1_w = unname(unlist(atlantis.meanSizeByAge["CohoOY_Fish1"])),
      CohoOY_Fish2_w = unname(unlist(atlantis.meanSizeByAge["CohoOY_Fish2"])),
      CohoOY_Fish3_w = unname(unlist(atlantis.meanSizeByAge["CohoOY_Fish3"])), 
      
      CohoRes_Fish1_w = unname(unlist(atlantis.meanSizeByAge["CohoRes_Fish1"])),
      CohoRes_Fish2_w = unname(unlist(atlantis.meanSizeByAge["CohoRes_Fish2"])),
      CohoRes_Fish3_w = unname(unlist(atlantis.meanSizeByAge["CohoRes_Fish3"])), 
      
      CohoResD_Fish1_w = unname(unlist(atlantis.meanSizeByAge["CohoResD_Fish1"])),
      CohoResD_Fish2_w = unname(unlist(atlantis.meanSizeByAge["CohoResD_Fish2"])),
      CohoResD_Fish3_w = unname(unlist(atlantis.meanSizeByAge["CohoResD_Fish3"])), 
      
      CohoSY_Fish1_w = unname(unlist(atlantis.meanSizeByAge["CohoSY_Fish1"])),
      CohoSY_Fish2_w = unname(unlist(atlantis.meanSizeByAge["CohoSY_Fish2"])),
      CohoSY_Fish3_w = unname(unlist(atlantis.meanSizeByAge["CohoSY_Fish3"])), 
      
      DemRock_Fish1_w = unname(unlist(atlantis.meanSizeByAge["DemRock_Fish1"])), 
      DemRock_Fish10_w = unname(unlist(atlantis.meanSizeByAge["DemRock_Fish10"])),
      DemRock_Fish2_w = unname(unlist(atlantis.meanSizeByAge["DemRock_Fish2"])),
      DemRock_Fish3_w = unname(unlist(atlantis.meanSizeByAge["DemRock_Fish3"])),
      DemRock_Fish4_w = unname(unlist(atlantis.meanSizeByAge["DemRock_Fish4"])),
      DemRock_Fish5_w = unname(unlist(atlantis.meanSizeByAge["DemRock_Fish5"])),
      DemRock_Fish6_w = unname(unlist(atlantis.meanSizeByAge["DemRock_Fish6"])),
      DemRock_Fish7_w = unname(unlist(atlantis.meanSizeByAge["DemRock_Fish7"])),
      DemRock_Fish8_w = unname(unlist(atlantis.meanSizeByAge["DemRock_Fish8"])),
      DemRock_Fish9_w = unname(unlist(atlantis.meanSizeByAge["DemRock_Fish9"])), 
      
      DemVRock_Fish1_w = unname(unlist(atlantis.meanSizeByAge["DemVRock_Fish1"])), 
      DemVRock_Fish10_w = unname(unlist(atlantis.meanSizeByAge["DemVRock_Fish10"])),
      DemVRock_Fish2_w = unname(unlist(atlantis.meanSizeByAge["DemVRock_Fish2"])),
      DemVRock_Fish3_w = unname(unlist(atlantis.meanSizeByAge["DemVRock_Fish3"])),
      DemVRock_Fish4_w = unname(unlist(atlantis.meanSizeByAge["DemVRock_Fish4"])),
      DemVRock_Fish5_w = unname(unlist(atlantis.meanSizeByAge["DemVRock_Fish5"])),
      DemVRock_Fish6_w = unname(unlist(atlantis.meanSizeByAge["DemVRock_Fish6"])),
      DemVRock_Fish7_w = unname(unlist(atlantis.meanSizeByAge["DemVRock_Fish7"])),
      DemVRock_Fish8_w = unname(unlist(atlantis.meanSizeByAge["DemVRock_Fish8"])),
      DemVRock_Fish9_w = unname(unlist(atlantis.meanSizeByAge["DemVRock_Fish9"])), 
      
      Gadiods_Fish1_w = unname(unlist(atlantis.meanSizeByAge["Gadiods_Fish1"])), 
      Gadiods_Fish10_w = unname(unlist(atlantis.meanSizeByAge["Gadiods_Fish10"])),
      Gadiods_Fish2_w = unname(unlist(atlantis.meanSizeByAge["Gadiods_Fish2"])),
      Gadiods_Fish3_w = unname(unlist(atlantis.meanSizeByAge["Gadiods_Fish3"])),
      Gadiods_Fish4_w = unname(unlist(atlantis.meanSizeByAge["Gadiods_Fish4"])),
      Gadiods_Fish5_w = unname(unlist(atlantis.meanSizeByAge["Gadiods_Fish5"])),
      Gadiods_Fish6_w = unname(unlist(atlantis.meanSizeByAge["Gadiods_Fish6"])),
      Gadiods_Fish7_w = unname(unlist(atlantis.meanSizeByAge["Gadiods_Fish7"])),
      Gadiods_Fish8_w = unname(unlist(atlantis.meanSizeByAge["Gadiods_Fish8"])),
      Gadiods_Fish9_w = unname(unlist(atlantis.meanSizeByAge["Gadiods_Fish9"])), 
      
      Harbor_seal1_w = unname(unlist(atlantis.meanSizeByAge["Harbor_seal1"])), 
      Harbor_seal10_w = unname(unlist(atlantis.meanSizeByAge["Harbor_seal10"])),
      Harbor_seal2_w = unname(unlist(atlantis.meanSizeByAge["Harbor_seal2"])),
      Harbor_seal3_w = unname(unlist(atlantis.meanSizeByAge["Harbor_seal3"])),
      Harbor_seal4_w = unname(unlist(atlantis.meanSizeByAge["Harbor_seal4"])),
      Harbor_seal5_w = unname(unlist(atlantis.meanSizeByAge["Harbor_seal5"])),
      Harbor_seal6_w = unname(unlist(atlantis.meanSizeByAge["Harbor_seal6"])),
      Harbor_seal7_w = unname(unlist(atlantis.meanSizeByAge["Harbor_seal7"])),
      Harbor_seal8_w = unname(unlist(atlantis.meanSizeByAge["Harbor_seal8"])),
      Harbor_seal9_w = unname(unlist(atlantis.meanSizeByAge["Harbor_seal9"])), 
      
      Herring_Cherry1_w = unname(unlist(atlantis.meanSizeByAge["Herring_Cherry1"])),
      Herring_Cherry2_w = unname(unlist(atlantis.meanSizeByAge["Herring_Cherry2"])),
      Herring_Cherry3_w = unname(unlist(atlantis.meanSizeByAge["Herring_Cherry3"])),
      Herring_Cherry4_w = unname(unlist(atlantis.meanSizeByAge["Herring_Cherry4"])),
      Herring_Cherry5_w = unname(unlist(atlantis.meanSizeByAge["Herring_Cherry5"])),
      Herring_Cherry6_w = unname(unlist(atlantis.meanSizeByAge["Herring_Cherry6"])), 
      
      Herring_PS1_w = unname(unlist(atlantis.meanSizeByAge["Herring_PS1"])),
      Herring_PS2_w = unname(unlist(atlantis.meanSizeByAge["Herring_PS2"])),
      Herring_PS3_w = unname(unlist(atlantis.meanSizeByAge["Herring_PS3"])),
      Herring_PS4_w = unname(unlist(atlantis.meanSizeByAge["Herring_PS4"])),
      Herring_PS5_w = unname(unlist(atlantis.meanSizeByAge["Herring_PS5"])),
      Herring_PS6_w = unname(unlist(atlantis.meanSizeByAge["Herring_PS6"])),
      Herring_PS7_w = unname(unlist(atlantis.meanSizeByAge["Herring_PS7"])), 
      
      Hump_whale1_w = unname(unlist(atlantis.meanSizeByAge["Hump_whale1"])),
      Hump_whale10_w = unname(unlist(atlantis.meanSizeByAge["Hump_whale10"])),
      Hump_whale2_w = unname(unlist(atlantis.meanSizeByAge["Hump_whale2"])),
      Hump_whale3_w = unname(unlist(atlantis.meanSizeByAge["Hump_whale3"])),
      Hump_whale4_w = unname(unlist(atlantis.meanSizeByAge["Hump_whale4"])),
      Hump_whale5_w = unname(unlist(atlantis.meanSizeByAge["Hump_whale5"])),
      Hump_whale6_w = unname(unlist(atlantis.meanSizeByAge["Hump_whale6"])),
      Hump_whale7_w = unname(unlist(atlantis.meanSizeByAge["Hump_whale7"])),
      Hump_whale8_w = unname(unlist(atlantis.meanSizeByAge["Hump_whale8"])), 
      Hump_whale9_w = unname(unlist(atlantis.meanSizeByAge["Hump_whale9"])), 
      
      LgDem_Fish1_w = unname(unlist(atlantis.meanSizeByAge["LgDem_Fish1"])), 
      LgDem_Fish10_w = unname(unlist(atlantis.meanSizeByAge["LgDem_Fish10"])),
      LgDem_Fish2_w = unname(unlist(atlantis.meanSizeByAge["LgDem_Fish2"])),
      LgDem_Fish3_w = unname(unlist(atlantis.meanSizeByAge["LgDem_Fish3"])),
      LgDem_Fish4_w = unname(unlist(atlantis.meanSizeByAge["LgDem_Fish4"])),
      LgDem_Fish5_w = unname(unlist(atlantis.meanSizeByAge["LgDem_Fish5"])),
      LgDem_Fish6_w = unname(unlist(atlantis.meanSizeByAge["LgDem_Fish6"])),
      LgDem_Fish7_w = unname(unlist(atlantis.meanSizeByAge["LgDem_Fish7"])),
      LgDem_Fish8_w = unname(unlist(atlantis.meanSizeByAge["LgDem_Fish8"])),
      LgDem_Fish9_w = unname(unlist(atlantis.meanSizeByAge["LgDem_Fish9"])), 
      
      MidRock_Fish1_w = unname(unlist(atlantis.meanSizeByAge["MidRock_Fish1"])),
      MidRock_Fish10_w = unname(unlist(atlantis.meanSizeByAge["MidRock_Fish10"])),
      MidRock_Fish2_w = unname(unlist(atlantis.meanSizeByAge["MidRock_Fish2"])),
      MidRock_Fish3_w = unname(unlist(atlantis.meanSizeByAge["MidRock_Fish3"])),
      MidRock_Fish4_w = unname(unlist(atlantis.meanSizeByAge["MidRock_Fish4"])),
      MidRock_Fish5_w = unname(unlist(atlantis.meanSizeByAge["MidRock_Fish5"])),
      MidRock_Fish6_w = unname(unlist(atlantis.meanSizeByAge["MidRock_Fish6"])),
      MidRock_Fish7_w = unname(unlist(atlantis.meanSizeByAge["MidRock_Fish7"])),
      MidRock_Fish8_w = unname(unlist(atlantis.meanSizeByAge["MidRock_Fish8"])),
      MidRock_Fish9_w = unname(unlist(atlantis.meanSizeByAge["MidRock_Fish9"])), 
      
      MidVRock_Fish1_w = unname(unlist(atlantis.meanSizeByAge["MidVRock_Fish1"])), 
      MidVRock_Fish10_w = unname(unlist(atlantis.meanSizeByAge["MidVRock_Fish10"])), 
      MidVRock_Fish2_w = unname(unlist(atlantis.meanSizeByAge["MidVRock_Fish2"])),
      MidVRock_Fish3_w = unname(unlist(atlantis.meanSizeByAge["MidVRock_Fish3"])),
      MidVRock_Fish4_w = unname(unlist(atlantis.meanSizeByAge["MidVRock_Fish4"])),
      MidVRock_Fish5_w = unname(unlist(atlantis.meanSizeByAge["MidVRock_Fish5"])),
      MidVRock_Fish6_w = unname(unlist(atlantis.meanSizeByAge["MidVRock_Fish6"])),
      MidVRock_Fish7_w = unname(unlist(atlantis.meanSizeByAge["MidVRock_Fish7"])),
      MidVRock_Fish8_w = unname(unlist(atlantis.meanSizeByAge["MidVRock_Fish8"])),
      MidVRock_Fish9_w = unname(unlist(atlantis.meanSizeByAge["MidVRock_Fish9"])), 
      
      NonPisc_Seabird1_w = unname(unlist(atlantis.meanSizeByAge["NonPisc_Seabird1"])),
      NonPisc_Seabird10_w = unname(unlist(atlantis.meanSizeByAge["NonPisc_Seabird10"])),
      NonPisc_Seabird2_w = unname(unlist(atlantis.meanSizeByAge["NonPisc_Seabird2"])),
      NonPisc_Seabird3_w = unname(unlist(atlantis.meanSizeByAge["NonPisc_Seabird3"])),
      NonPisc_Seabird4_w = unname(unlist(atlantis.meanSizeByAge["NonPisc_Seabird4"])),
      NonPisc_Seabird5_w = unname(unlist(atlantis.meanSizeByAge["NonPisc_Seabird5"])),
      NonPisc_Seabird6_w = unname(unlist(atlantis.meanSizeByAge["NonPisc_Seabird6"])),
      NonPisc_Seabird7_w = unname(unlist(atlantis.meanSizeByAge["NonPisc_Seabird7"])),
      NonPisc_Seabird8_w = unname(unlist(atlantis.meanSizeByAge["NonPisc_Seabird8"])),
      NonPisc_Seabird9_w = unname(unlist(atlantis.meanSizeByAge["NonPisc_Seabird9"])), 
      
      OtherSal_Fish1_w = unname(unlist(atlantis.meanSizeByAge["OtherSal_Fish1"])),
      OtherSal_Fish2_w = unname(unlist(atlantis.meanSizeByAge["OtherSal_Fish2"])),
      OtherSal_Fish3_w = unname(unlist(atlantis.meanSizeByAge["OtherSal_Fish3"])),
      OtherSal_Fish4_w = unname(unlist(atlantis.meanSizeByAge["OtherSal_Fish4"])),
      OtherSal_Fish5_w = unname(unlist(atlantis.meanSizeByAge["OtherSal_Fish5"])),
      OtherSal_Fish6_w = unname(unlist(atlantis.meanSizeByAge["OtherSal_Fish6"])),
      OtherSal_Fish7_w = unname(unlist(atlantis.meanSizeByAge["OtherSal_Fish7"])),
      OtherSal_Fish8_w = unname(unlist(atlantis.meanSizeByAge["OtherSal_Fish8"])), 
      
      Perch_Fish1_w = unname(unlist(atlantis.meanSizeByAge["Perch_Fish1"])),
      Perch_Fish2_w = unname(unlist(atlantis.meanSizeByAge["Perch_Fish2"])),
      Perch_Fish3_w = unname(unlist(atlantis.meanSizeByAge["Perch_Fish3"])),
      Perch_Fish4_w = unname(unlist(atlantis.meanSizeByAge["Perch_Fish4"])),
      Perch_Fish5_w = unname(unlist(atlantis.meanSizeByAge["Perch_Fish5"])),
      Perch_Fish6_w = unname(unlist(atlantis.meanSizeByAge["Perch_Fish6"])),
      Perch_Fish7_w = unname(unlist(atlantis.meanSizeByAge["Perch_Fish7"])),
      Perch_Fish8_w = unname(unlist(atlantis.meanSizeByAge["Perch_Fish8"])), 
      
      PinkSY_Fish1_w = unname(unlist(atlantis.meanSizeByAge["PinkSY_Fish1"])),
      PinkSY_Fish2_w = unname(unlist(atlantis.meanSizeByAge["PinkSY_Fish2"])),
      PinkSY_Fish3_w = unname(unlist(atlantis.meanSizeByAge["PinkSY_Fish3"])), 
      
      Pinniped1_w = unname(unlist(atlantis.meanSizeByAge["Pinniped1"])), 
      Pinniped10_w = unname(unlist(atlantis.meanSizeByAge["Pinniped10"])), 
      Pinniped2_w = unname(unlist(atlantis.meanSizeByAge["Pinniped2"])),
      Pinniped3_w = unname(unlist(atlantis.meanSizeByAge["Pinniped3"])),
      Pinniped4_w = unname(unlist(atlantis.meanSizeByAge["Pinniped4"])),
      Pinniped5_w = unname(unlist(atlantis.meanSizeByAge["Pinniped5"])),
      Pinniped6_w = unname(unlist(atlantis.meanSizeByAge["Pinniped6"])),
      Pinniped7_w = unname(unlist(atlantis.meanSizeByAge["Pinniped7"])),
      Pinniped8_w = unname(unlist(atlantis.meanSizeByAge["Pinniped8"])),
      Pinniped9_w = unname(unlist(atlantis.meanSizeByAge["Pinniped9"])), 
      
      Pisc_Seabird1_w = unname(unlist(atlantis.meanSizeByAge["Pisc_Seabird1"])),
      Pisc_Seabird10_w = unname(unlist(atlantis.meanSizeByAge["Pisc_Seabird10"])),
      Pisc_Seabird2_w = unname(unlist(atlantis.meanSizeByAge["Pisc_Seabird2"])),
      Pisc_Seabird3_w = unname(unlist(atlantis.meanSizeByAge["Pisc_Seabird3"])),
      Pisc_Seabird4_w = unname(unlist(atlantis.meanSizeByAge["Pisc_Seabird4"])),
      Pisc_Seabird5_w = unname(unlist(atlantis.meanSizeByAge["Pisc_Seabird5"])),
      Pisc_Seabird6_w = unname(unlist(atlantis.meanSizeByAge["Pisc_Seabird6"])),
      Pisc_Seabird7_w = unname(unlist(atlantis.meanSizeByAge["Pisc_Seabird7"])),
      Pisc_Seabird8_w = unname(unlist(atlantis.meanSizeByAge["Pisc_Seabird8"])),
      Pisc_Seabird9_w = unname(unlist(atlantis.meanSizeByAge["Pisc_Seabird9"])), 
      
      PiscFlat_Fish1_w = unname(unlist(atlantis.meanSizeByAge["PiscFlat_Fish1"])),
      PiscFlat_Fish10_w = unname(unlist(atlantis.meanSizeByAge["PiscFlat_Fish10"])),
      PiscFlat_Fish2_w = unname(unlist(atlantis.meanSizeByAge["PiscFlat_Fish2"])),
      PiscFlat_Fish3_w = unname(unlist(atlantis.meanSizeByAge["PiscFlat_Fish3"])),
      PiscFlat_Fish4_w = unname(unlist(atlantis.meanSizeByAge["PiscFlat_Fish4"])),
      PiscFlat_Fish5_w = unname(unlist(atlantis.meanSizeByAge["PiscFlat_Fish5"])),
      PiscFlat_Fish6_w = unname(unlist(atlantis.meanSizeByAge["PiscFlat_Fish6"])),
      PiscFlat_Fish7_w = unname(unlist(atlantis.meanSizeByAge["PiscFlat_Fish7"])),
      PiscFlat_Fish8_w = unname(unlist(atlantis.meanSizeByAge["PiscFlat_Fish8"])),
      PiscFlat_Fish9_w = unname(unlist(atlantis.meanSizeByAge["PiscFlat_Fish9"])), 
      
      Porpoise1_w = unname(unlist(atlantis.meanSizeByAge["Porpoise1"])), 
      Porpoise10_w = unname(unlist(atlantis.meanSizeByAge["Porpoise10"])),
      Porpoise2_w = unname(unlist(atlantis.meanSizeByAge["Porpoise2"])),
      Porpoise3_w = unname(unlist(atlantis.meanSizeByAge["Porpoise3"])),
      Porpoise4_w = unname(unlist(atlantis.meanSizeByAge["Porpoise4"])),
      Porpoise5_w = unname(unlist(atlantis.meanSizeByAge["Porpoise5"])),
      Porpoise6_w = unname(unlist(atlantis.meanSizeByAge["Porpoise6"])),
      Porpoise7_w = unname(unlist(atlantis.meanSizeByAge["Porpoise7"])),
      Porpoise8_w = unname(unlist(atlantis.meanSizeByAge["Porpoise8"])),
      Porpoise9_w = unname(unlist(atlantis.meanSizeByAge["Porpoise9"])), 
      
      Raptors1_w = unname(unlist(atlantis.meanSizeByAge["Raptors1"])), 
      Raptors10_w = unname(unlist(atlantis.meanSizeByAge["Raptors10"])),
      Raptors2_w = unname(unlist(atlantis.meanSizeByAge["Raptors2"])),
      Raptors3_w = unname(unlist(atlantis.meanSizeByAge["Raptors3"])),
      Raptors4_w = unname(unlist(atlantis.meanSizeByAge["Raptors4"])),
      Raptors5_w = unname(unlist(atlantis.meanSizeByAge["Raptors5"])),
      Raptors6_w = unname(unlist(atlantis.meanSizeByAge["Raptors6"])),
      Raptors7_w = unname(unlist(atlantis.meanSizeByAge["Raptors7"])),
      Raptors8_w = unname(unlist(atlantis.meanSizeByAge["Raptors8"])),
      Raptors9_w = unname(unlist(atlantis.meanSizeByAge["Raptors9"])), 
      
      Ratfish1_w = unname(unlist(atlantis.meanSizeByAge["Ratfish1"])), 
      Ratfish10_w = unname(unlist(atlantis.meanSizeByAge["Ratfish10"])),
      Ratfish2_w = unname(unlist(atlantis.meanSizeByAge["Ratfish2"])),
      Ratfish3_w = unname(unlist(atlantis.meanSizeByAge["Ratfish3"])),
      Ratfish4_w = unname(unlist(atlantis.meanSizeByAge["Ratfish4"])),
      Ratfish5_w = unname(unlist(atlantis.meanSizeByAge["Ratfish5"])),
      Ratfish6_w = unname(unlist(atlantis.meanSizeByAge["Ratfish6"])),
      Ratfish7_w = unname(unlist(atlantis.meanSizeByAge["Ratfish7"])),
      Ratfish8_w = unname(unlist(atlantis.meanSizeByAge["Ratfish8"])),
      Ratfish9_w = unname(unlist(atlantis.meanSizeByAge["Ratfish9"])), 
      
      Res_Orca1_w = unname(unlist(atlantis.meanSizeByAge["Res_Orca1"])), 
      Res_Orca10_w = unname(unlist(atlantis.meanSizeByAge["Res_Orca10"])), 
      Res_Orca2_w = unname(unlist(atlantis.meanSizeByAge["Res_Orca2"])),
      Res_Orca3_w = unname(unlist(atlantis.meanSizeByAge["Res_Orca3"])),
      Res_Orca4_w = unname(unlist(atlantis.meanSizeByAge["Res_Orca4"])),
      Res_Orca5_w = unname(unlist(atlantis.meanSizeByAge["Res_Orca5"])),
      Res_Orca6_w = unname(unlist(atlantis.meanSizeByAge["Res_Orca6"])),
      Res_Orca7_w = unname(unlist(atlantis.meanSizeByAge["Res_Orca7"])),
      Res_Orca8_w = unname(unlist(atlantis.meanSizeByAge["Res_Orca8"])),
      Res_Orca9_w = unname(unlist(atlantis.meanSizeByAge["Res_Orca9"])), 
      
      SGeorgia_Fish1_w = unname(unlist(atlantis.meanSizeByAge["SGeorgia_Fish1"])),
      SGeorgia_Fish2_w = unname(unlist(atlantis.meanSizeByAge["SGeorgia_Fish2"])),
      SGeorgia_Fish3_w = unname(unlist(atlantis.meanSizeByAge["SGeorgia_Fish3"])),
      SGeorgia_Fish4_w = unname(unlist(atlantis.meanSizeByAge["SGeorgia_Fish4"])),
      SGeorgia_Fish5_w = unname(unlist(atlantis.meanSizeByAge["SGeorgia_Fish5"])), 
      
      Sixgill_Shark1_w = unname(unlist(atlantis.meanSizeByAge["Sixgill_Shark1"])),
      Sixgill_Shark10_w = unname(unlist(atlantis.meanSizeByAge["Sixgill_Shark10"])), 
      Sixgill_Shark2_w = unname(unlist(atlantis.meanSizeByAge["Sixgill_Shark2"])),
      Sixgill_Shark3_w = unname(unlist(atlantis.meanSizeByAge["Sixgill_Shark3"])),
      Sixgill_Shark4_w = unname(unlist(atlantis.meanSizeByAge["Sixgill_Shark4"])),
      Sixgill_Shark5_w = unname(unlist(atlantis.meanSizeByAge["Sixgill_Shark5"])),
      Sixgill_Shark6_w = unname(unlist(atlantis.meanSizeByAge["Sixgill_Shark6"])),
      Sixgill_Shark7_w = unname(unlist(atlantis.meanSizeByAge["Sixgill_Shark7"])),
      Sixgill_Shark8_w = unname(unlist(atlantis.meanSizeByAge["Sixgill_Shark8"])),
      Sixgill_Shark9_w = unname(unlist(atlantis.meanSizeByAge["Sixgill_Shark9"])), 
      
      SkateRay1_w = unname(unlist(atlantis.meanSizeByAge["SkateRay1"])), 
      SkateRay10_w = unname(unlist(atlantis.meanSizeByAge["SkateRay10"])),
      SkateRay2_w = unname(unlist(atlantis.meanSizeByAge["SkateRay2"])),
      SkateRay3_w = unname(unlist(atlantis.meanSizeByAge["SkateRay3"])),
      SkateRay4_w = unname(unlist(atlantis.meanSizeByAge["SkateRay4"])),
      SkateRay5_w = unname(unlist(atlantis.meanSizeByAge["SkateRay5"])),
      SkateRay6_w = unname(unlist(atlantis.meanSizeByAge["SkateRay6"])),
      SkateRay7_w = unname(unlist(atlantis.meanSizeByAge["SkateRay7"])),
      SkateRay8_w = unname(unlist(atlantis.meanSizeByAge["SkateRay8"])),
      SkateRay9_w = unname(unlist(atlantis.meanSizeByAge["SkateRay9"])), 
      
      Sm_Plank_Fish1_w = unname(unlist(atlantis.meanSizeByAge["Sm_Plank_Fish1"])),
      Sm_Plank_Fish2_w = unname(unlist(atlantis.meanSizeByAge["Sm_Plank_Fish2"])),
      Sm_Plank_Fish3_w = unname(unlist(atlantis.meanSizeByAge["Sm_Plank_Fish3"])),
      Sm_Plank_Fish4_w = unname(unlist(atlantis.meanSizeByAge["Sm_Plank_Fish4"])),
      Sm_Plank_Fish5_w = unname(unlist(atlantis.meanSizeByAge["Sm_Plank_Fish5"])),
      Sm_Plank_Fish6_w = unname(unlist(atlantis.meanSizeByAge["Sm_Plank_Fish6"])),
      Sm_Plank_Fish7_w = unname(unlist(atlantis.meanSizeByAge["Sm_Plank_Fish7"])),
      Sm_Plank_Fish8_w = unname(unlist(atlantis.meanSizeByAge["Sm_Plank_Fish8"])), 
      
      SmDem_Fish1_w = unname(unlist(atlantis.meanSizeByAge["SmDem_Fish1"])),
      SmDem_Fish2_w = unname(unlist(atlantis.meanSizeByAge["SmDem_Fish2"])),
      SmDem_Fish3_w = unname(unlist(atlantis.meanSizeByAge["SmDem_Fish3"])),
      SmDem_Fish4_w = unname(unlist(atlantis.meanSizeByAge["SmDem_Fish4"])),
      SmDem_Fish5_w = unname(unlist(atlantis.meanSizeByAge["SmDem_Fish5"])), 
      
      SmFlat_Fish1_w = unname(unlist(atlantis.meanSizeByAge["SmFlat_Fish1"])),
      SmFlat_Fish10_w = unname(unlist(atlantis.meanSizeByAge["SmFlat_Fish10"])),
      SmFlat_Fish2_w = unname(unlist(atlantis.meanSizeByAge["SmFlat_Fish2"])),
      SmFlat_Fish3_w = unname(unlist(atlantis.meanSizeByAge["SmFlat_Fish3"])),
      SmFlat_Fish4_w = unname(unlist(atlantis.meanSizeByAge["SmFlat_Fish4"])),
      SmFlat_Fish5_w = unname(unlist(atlantis.meanSizeByAge["SmFlat_Fish5"])),
      SmFlat_Fish6_w = unname(unlist(atlantis.meanSizeByAge["SmFlat_Fish6"])),
      SmFlat_Fish7_w = unname(unlist(atlantis.meanSizeByAge["SmFlat_Fish7"])),
      SmFlat_Fish8_w = unname(unlist(atlantis.meanSizeByAge["SmFlat_Fish8"])),
      SmFlat_Fish9_w = unname(unlist(atlantis.meanSizeByAge["SmFlat_Fish9"])), 
      
      Spinydog_Fish1_w = unname(unlist(atlantis.meanSizeByAge["Spinydog_Fish1"])), 
      Spinydog_Fish10_w = unname(unlist(atlantis.meanSizeByAge["Spinydog_Fish10"])), 
      Spinydog_Fish2_w = unname(unlist(atlantis.meanSizeByAge["Spinydog_Fish2"])),
      Spinydog_Fish3_w = unname(unlist(atlantis.meanSizeByAge["Spinydog_Fish3"])),
      Spinydog_Fish4_w = unname(unlist(atlantis.meanSizeByAge["Spinydog_Fish4"])),
      Spinydog_Fish5_w = unname(unlist(atlantis.meanSizeByAge["Spinydog_Fish5"])),
      Spinydog_Fish6_w = unname(unlist(atlantis.meanSizeByAge["Spinydog_Fish6"])),
      Spinydog_Fish7_w = unname(unlist(atlantis.meanSizeByAge["Spinydog_Fish7"])),
      Spinydog_Fish8_w = unname(unlist(atlantis.meanSizeByAge["Spinydog_Fish8"])),
      Spinydog_Fish9_w = unname(unlist(atlantis.meanSizeByAge["Spinydog_Fish9"])), 
      
      Trans_Orca1_w = unname(unlist(atlantis.meanSizeByAge["Trans_Orca1"])),
      Trans_Orca10_w = unname(unlist(atlantis.meanSizeByAge["Trans_Orca10"])),
      Trans_Orca2_w = unname(unlist(atlantis.meanSizeByAge["Trans_Orca2"])),
      Trans_Orca3_w = unname(unlist(atlantis.meanSizeByAge["Trans_Orca3"])),
      Trans_Orca4_w = unname(unlist(atlantis.meanSizeByAge["Trans_Orca4"])),
      Trans_Orca5_w = unname(unlist(atlantis.meanSizeByAge["Trans_Orca5"])),
      Trans_Orca6_w = unname(unlist(atlantis.meanSizeByAge["Trans_Orca6"])),
      Trans_Orca7_w = unname(unlist(atlantis.meanSizeByAge["Trans_Orca7"])),
      Trans_Orca8_w = unname(unlist(atlantis.meanSizeByAge["Trans_Orca8"])),
      Trans_Orca9_w = unname(unlist(atlantis.meanSizeByAge["Trans_Orca9"]))
      
      )

  }
    return(output)

}
